### ISSUE TITLE
Test a 20K report with 2 threads and 250 hosts (auto-scale 1)

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#185]
Test a 20K report with 2 threads and 250 hosts (auto-scale 1).  We would like a timing of how long it takes to process this report so we can determine appropriate scaling.

**Comment by abaiken** [comment]
So the good news is that PROD seems to be incredibly fast and is working correctly. I deployed to PROD with the following specs: 
```
autoscale max pods: 1 
max threads: 2
hosts_per_req: 250
```
I then uploaded a report that had a total of 20,425 hosts (broken into 3 slices 6809/6809/6807). Here were the time stats for the above report: 
```
2019-07-01 20:42:15,221 \| INFO \| abstract_processor.py:log_time_stats:499 \| Report(account=6175170, report_platform_id=109a8a06-3503-4c87-9ebb-fbcb52131603) REPORT TIME STATS -
--
  | Arrival date & time: 2019-07-01: 20:37:17.00
  | Time spent in queue: 0h 0m 41s
  | Time spent processing report: 0h 4m 15s
  | Completion date & time: 2019-07-01: 20:42:14.00
```
