### ISSUE TITLE
Toggle HOST_INVENTORY_UPLOAD_MODE flag to use Kafka when Host Inventory deploys kafka based upload to QA/Performance/Prod

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#219]
- [x] Change `HOST_INVENTORY_UPLOAD_MODE` to kafka for QA
- [x] Change `HOST_INVENTORY_UPLOAD_MODE` to kafka for PROD

**Comment by abaiken** [comment]
As of 9/23 kafka ingestion for uploading to HBI is still waiting for the QA team to sign off on it & has not been promoted to PROD

**Comment by abaiken** [comment]
Both `subscriptions-qa` and `subscriptions-prod` are using KAFKA to upload hosts to HBI now!
