### ISSUE TITLE
Vacuum our DB

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#256]
## Feature description:
Vacuum our DB

**Comment by abaiken** [comment]
Closing this because AWS enables auto-vacuuming by default. You can read more in the [docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.Autovacuum).
