### ISSUE TITLE
Update local development environment to use Insights Ingress Go instead of file upload

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#270]
## Feature description:

https://github.com/RedHatInsights/insights-ingress-go

**Comment by myersCody** [comment]
I played around with this today: 
Following their readme all I did a git clone and then try to run the command:
`docker-compose up --build`
resulted in the following error: 
```
Recreating insightsingressgo_ingress_1 ... error

ERROR: for insightsingressgo_ingress_1  Cannot start service ingress: oci runtime error: container_linux.go:265: starting container process caused "exec: \"app\": executable file not found in $PATH"


ERROR: for ingress  Cannot start service ingress: oci runtime error: container_linux.go:265: starting container process caused "exec:\"app\": executable file not found in $PATH"

ERROR: Encountered errors while bringing up the project.
```
I think a change in the insights-ingress-go dockerfile will be required in order to get this working.

**Comment by myersCody** [comment]
> I played around with this today:
> Following their readme all I did a git clone and then try to run the command:
> `docker-compose up --build`
> resulted in the following error:
> 
> ```
> Recreating insightsingressgo_ingress_1 ... error
> 
> ERROR: for insightsingressgo_ingress_1  Cannot start service ingress: oci runtime error: container_linux.go:265: starting container process caused "exec: \"app\": executable file not found in $PATH"
> 
> 
> ERROR: for ingress  Cannot start service ingress: oci runtime error: container_linux.go:265: starting container process caused "exec:\"app\": executable file not found in $PATH"
> 
> ERROR: Encountered errors while bringing up the project.
> ```
> 
> I think a change in the insights-ingress-go dockerfile will be required in order to get this working.

I reached out to Steven Adams about this issue and he pushed up a fix for us: https://github.com/RedHatInsights/insights-ingress-go/commit/82ffd56162d444c27228ac33dc28361a90cf6423

**Comment by myersCody** [comment]
Currently within the insights-ingress-go repo their was no way to add to the valid topics without manually changing the docker-compose file. Which we could have handled through a sed replacement; however, instead I have opened a pr to allow the valid topics to be a variable inside of the .env file to allow us to overwrite it with our upload_env file for local development.

pr: https://github.com/RedHatInsights/insights-ingress-go/pull/112

**Comment by myersCody** [comment]
https://github.com/quipucords/yupana/pull/276
