### ISSUE TITLE
User Story: yupana should add system culling dates for HBI

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#280]
@kholdaway commented on [Mon Nov 04 2019](https://github.com/quipucords/quipucords/issues/2015)

## Feature description:

See HBI culling https://docs.google.com/document/d/1s2qoB-tChStxRXey1bNXg6AjSMFw0ErGZmlla3HOCLo/edit

**Comment by abaiken** [comment]
waiting on https://github.com/RedHatInsights/e2e-deploy/pull/838
