### ISSUE TITLE
User Story: Create product manifest for product security consumption.

### ISSUE THREAD

**Issue by abaiken** [quipucords/yupana#287]
## Feature Description
As a service developer, I want to be able to provide a manifest of the run-time dependencies in a machine readable fashion so that product security can review dependencies for any needed vulnerability remediation.

## Implementation Details
Another application (python 3.6) has created a manifest in the following fashion:
[Drift app - manifest creation](https://github.com/RedHatInsights/drift-backend/search?q=manifest&unscoped_q=manifest)

We can review and iterate as necessary. We would like perform this update as part of our make requirements target.
___

## Acceptance Criteria:

- [ ]  We produce a manifest file of dependencies that is consumable by product security.
- [ ]  We fail travis builds if dependencies are changed but the manifest is not updated.

**Comment by kholdaway** [comment]
@abaiken how is this different from #286 :trollface:

**Comment by abaiken** [comment]
Closing in favor of https://github.com/quipucords/yupana/issues/286 😂
