### ISSUE TITLE
User Story: Deploy to Insights Stage/Production

### ISSUE THREAD

**Issue by abaiken** [quipucords/yupana#38]
- Deploy to Insights Staging 
- Deploy to Insights Production 
- Add RDS to deployments for Stage/Production

**Comment by kholdaway** [comment]
See https://projects.engineering.redhat.com/browse/RHIOPS-109

**Comment by abaiken** [comment]
Deployed via jenkins jobs: 
https://sonar-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/deploy-yupana-prod/
https://sonar-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/deploy-yupana-stage/
