### ISSUE TITLE
User Story: Instrument status API with Prometheus metric as required by insights platform

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#46]
## Feature description:

There are several reference documents around this issue:
- https://docs.google.com/document/d/1NOAFwTXg5pD7jNKRspBimO_uKZ0Rj1Vb0va4RjtgiMw/edit
- https://github.com/gavin-romig-koch/fakeE2EBlackbox
- https://github.com/prometheus/client_python

The goal is to add a single metric as requested.  We can add a status endpoint hit count to get started.

**Comment by abaiken** [comment]
closed by #72
