### ISSUE TITLE
Use Grafana dashboard to display prometheus data 

### ISSUE THREAD

**Issue by abaiken** [quipucords/yupana#78]
## Feature description:
Need to ask about steps to configure Grafana to display the data gathered from the metrics endpoint. If steps are required, we should complete them so that we can see our data. 

### Is your feature request related to a problem?
Right now prometheus is polling our `/metrics` endpoint but we should make sure that we can see this information in grafana. 

### Describe the solution you'd like
Possibly reach out to Stephen Adams to see what steps we need to take to configure Grafana. 

___

## Acceptance Criteria:

- [ ] Verify that we can view prometheus data using Grafana 

___

**Comment by abaiken** [comment]
[Here]( https://metrics-mnm-ci.5a9f.insights-dev.openshiftapps.com/d/_kvagEgWk/subscriptions-ci) are the graphs I created based on our prometheus metrics.

**Comment by myersCody** [comment]
Ash and I had a meeting today to go over this, and I think that the graphs she has created provides a great base for us to start with. I think as we go on we may want to add another graph, but that should be added as a separate issue/pr. So, I think this issue is ready to be closed.
